### PR TITLE
Fix pulp pull

### PR DESCRIPTION
**Pull request by twaugh**
It was needlessly retrying its requests for media types. We only need to retry if we see a 404 response.

Signed-off-by: Tim Waugh <twaugh@redhat.com>

### CODE REVIEW

**Comment by twaugh** [comment]
Hmm, needs work to fix coverage.

**Comment by rcerven** [comment]
why do we again wanna put retry logic into plugin? and only for 404?

**Comment by twaugh** [comment]
404 is not something that should be automatically retried in general. However, pulp_pull knows that there may be a good reason to retry when it sees 404 (see comment).

So the expectation here is that pulp_pull will handle retries for 404, only for the specific case of Crane not having spotted the new Pulp content yet.

For everything else: the GET requests used by get_manifest_digests(), the docker API calls, retries for retryable errors should be handled automatically "behind the scenes".

Does that explain it adequately?

**Comment by rcerven** [comment]
ok in that case at least move the retry function into utils so it can be used for anything else if needed

**Comment by twaugh** [comment]
I could move it there, but what else would use it?

**Comment by rcerven** [comment]
don't know, but seems weird put put again retry logic in plugin, when mine story is trying to get rid of it

**Comment by twaugh** [comment]
How about we leave this retry logic as-is for this PR, but if your retry-logic PR allows re-use of this type of code, let's try to merge them there?

**Pull request merged**
