### PR TITLE
add python{2,3}-pytest-runner to Requires: in spec when checks are run

### PR DESCRIPTION
**Pull request by maxamillion**
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>

### CODE REVIEW

**Comment by maxamillion** [comment]
@twaugh Either way :)

**Comment by lcarva** [comment]
Adding those dependencies would break stuff for rhel, as Tim mentioned.
Two possible alternate approaches:

1. Add `sed` in spec file to nuke `setup_requires` dependencies:
```
%prep
%setup -qn %{name}-%{commit}

sed -i '/setup_requires/d' setup.py
```

2. Modify `setup.py` to read `setup_requires` items from a file (like requirements.txt), and modify `spec` to clear that file.

**Comment by twaugh** [comment]
We should drop the pytest-runner dependency entirely and just document how to run tests, as in https://github.com/projectatomic/osbs-client/pull/503.

**Comment by lcarva** [comment]
@twaugh should this be dropped then?

**Comment by twaugh** [comment]
Yes.

**Pull request closed without merging**
