### PR TITLE
Fix sending the OAuth2 token to ODCS

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <patrick@puiterwijk.org>

### CODE REVIEW

**Comment by puiterwijk** [comment]
`OIDC_access_token` and `OIDC_CLAIM_scope` are environment variables set by mod_auth_openidc, when the client sends a token as a Bearer token.

**Comment by lcarva** [comment]
@puiterwijk, thanks for this!

We have recently moved the ODCSClient class to a new file `odcs_utils.py`.
Think you could rebase?

**Comment by puiterwijk** [comment]
@lcarva Done! And that has must been very recent then, I think :).

**Comment by lcarva** [comment]
This looks good to me, but I have no way of validating these changes work. That was also the case for the previous implementation btw.

The project's README still mentions setting the scopes: [Using OpenIDC for authentication](https://pagure.io/odcs)

Is that just bad documentation?

**Comment by puiterwijk** [comment]
@lcarva no, the documentation is correct, because they are passing that list of scopes to a python client that is used to actually get a token from the Identity Provider. That client does need the list of scopes so it knows what kind of token to request, but if you look at the way the ODCSClient is initialized, it does not get the list of scopes, because ODCS gets that list from the IdP:
````
odcs = ODCS("https://odcs.fedoraproject.org",
            auth_mech=AuthMech.OpenIDC,
            openidc_token="your_openidc_token")
````

**Comment by lcarva** [comment]
@puiterwijk, we're having issues with osbs-bot, any chance you can amend and push the commit to have it run again?

**Comment by lcarva** [comment]
I'm going to merge this because this is blocking my work in adding ssl auth support.

**Comment by lcarva** [comment]
Updated release notes draft:
> - Fix sending the OAuth2 token to ODCS

**Pull request merged**
