### PR TITLE
Don't log failures as errors in get_manifests()

### PR DESCRIPTION
**Pull request by twaugh**
Fixes OSBS-5453.

Signed-off-by: Tim Waugh <twaugh@redhat.com>

### CODE REVIEW

**Comment by mlangsdorf** [comment]
The comment "shouldn't log failures" in the unit tests is confusing. I've read the pydoc-catchlog docs twice and I'm still not 100% sure what is going on there.
I get that we want to fail if the warning messages are reported as errors, just not sure how you're testing that.

**Comment by twaugh** [comment]
I added some comments to hopefully make things clearer. The overall approach is: set the log level for captured messages to ERROR, then afterwards verify that no log messages were captured -- then we know no ERROR+ messages were logged.

**Comment by twaugh** [comment]
Will re-base after #995 is merged.

**Comment by mlangsdorf** [comment]
Thanks, that's a lot less cryptic.

**Pull request merged**
