### PR TITLE
Allow koji-related testing when koji module not installed

### PR DESCRIPTION
**Pull request by twaugh**

### CODE REVIEW

**Comment by twaugh** [comment]
This is what I meant earlier @pbabinca - now the `tests/plugins/test_koji.py` test runs.

**Comment by TomasTomecek** [comment]
Could `tests/koji/__init__.py` be mocked with flexmock? If not, I'm fine with merging this. @bkabrda can you take a look please?

**Comment by bkabrda** [comment]
AFAIK there's no way to improve this with flexmock, I would do it like this as well. So LGTM.

**Comment by twaugh** [comment]
It seems like you can't `flexmock()` anything that doesn't already exist in some form. The idea here is to make it exist in the most minimal form, and `flexmock()` it to use what we want while testing.

**Comment by TomasTomecek** [comment]
LGTM then

**Pull request merged**
