### PR TITLE
Fix pulp_pull media type checking

### PR DESCRIPTION
**Pull request by twaugh**
Signed-off-by: Tim Waugh <twaugh@redhat.com>

Not sure why the tests didn't spot this.

### CODE REVIEW

**Comment by twaugh** [comment]
The tests are fine, there doesn't seem to be any way to test for this failure. With recent Python versions these strings just get put into the same objects, even with explicit copy.

**Comment by twaugh** [comment]
@mlangsdorf, the reason this fix is required is that `is` is a test to see if the two things are the same object (i.e. `a is b` means `id(a) == id(b)`), whereas `==` is the less strict test to see if the two things compare as equal.

In day-to-day code, `is None` is the main case for using `is`.

**Comment by lcarva** [comment]
I saw this and thought it should work because the plugin uses the same constant. I realize now that it's not the same object because the value is being passed across systems.

**Comment by twaugh** [comment]
Ah, figured out how to make the test catch this: using `json.loads()`.

**Pull request merged**
