### PR TITLE
don't enclose base_image and parent_images when image is custom base …

### PR DESCRIPTION
**Pull request by rcerven**
…image

Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by rcerven** [comment]
we can't enclose custom base image, since that is just placeholder for us, and builder.parent_images has unmodified koji/image-build, so if we enclose it in change_in_df plugin, it will fail with parentimagemissing, because koji/image-build != organization/koji-image-build

**Comment by twaugh** [comment]
Would be nice to have a test case demonstrating it.

**Comment by rcerven** [comment]
added test case for that

**Comment by rcerven** [comment]
rn updated: - Custom base images work with organization defined

**Pull request merged**
