### PR TITLE
Move push_tar_to_pulp into atomic-reactor codebase

### PR DESCRIPTION
**Pull request by mmilata**
This should work with release-engineering/dockpulp master.

I tried to do some refactoring and broke the changes into multiple commits to make review easier. It would probably be better to squash them before merging.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
let's merge this after:
- [ ] updated dockpulp is released
- [ ] someone verified it's **really** working

**Comment by mmilata** [comment]
@TomasTomecek agreed.

**Comment by TomasTomecek** [comment]
LGTM

**Comment by mmilata** [comment]
So dockpulp is released and we can test it - https://github.com/release-engineering/dockpulp/releases/tag/dockpulp-1.12-5

Pushing to pulp works for me, can someone else test it too? @TomasTomecek, @twaugh?

**Comment by TomasTomecek** [comment]
seemed to work, except pulp timed out; started working on a test for pushing: https://github.com/projectatomic/atomic-reactor/pull/377

**Comment by twaugh** [comment]
Works in my testing. In fact, it fixes #387.

**Comment by TomasTomecek** [comment]
Thanks @mmilata, very nice work!

**Pull request merged**
