### PR TITLE
Avoid requiring pygit2 (fixes #305)

### LINKED ISSUE #305: bump_release: avoid pygit2 dependency
Availability of the `python-pygit2` package is limited, whereas the `git` binary is everywhere. We should avoid depending on pygit2 and instead use `git` directly.

### PR DESCRIPTION
**Pull request by twaugh**
It's still quite useful for testing the bump_release plugin so is used only for that.

Needs some testing.

### CODE REVIEW

**Comment by twaugh** [comment]
Tested now.

**Comment by twaugh** [comment]
I'd like to squash before merge.

**Comment by jpopelka** [comment]
LGTM

**Comment by twaugh** [comment]
Re-based and squashed.

**Pull request merged**
