### PR TITLE
Fail as soon as a required plugin fails (fixes #261)

### LINKED ISSUE #261: Plugin failure should fail the whole build
Plugins should fail the build and should "fail fast". If atomic-reactor can't import a plugin that user requested via `build.json` or that plugin fails, then the whole build should fail. I also think it should fail immediately, except perhaps exit plugins that get run either way.
The dangers of current behavior include
- delivering a different result that user wanted
- user not noticing that he got a different result, since atomic-reactor logs are pretty verbose and hard to read
Let's discuss :) @TomasTomecek @twaugh @mmilata @jpopelka

### PR DESCRIPTION
**Pull request by twaugh**
The only plugins that do not terminate the build are those with `can_fail=True` set, and exit plugins.

### CODE REVIEW

**Comment by twaugh** [comment]
Oh, please hold on this one.

**Comment by twaugh** [comment]
Re-based and adjusted so that a missing configured plugin causes a failure.

**Comment by TomasTomecek** [comment]
LGTM

**Comment by twaugh** [comment]
Clarifications added to comments.

**Comment by jpopelka** [comment]
LGTM

**Pull request merged**
