### PR TITLE
propagate logging level to osbs-client

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
IMHO it fixes issue with logging level, but the whole logging setting looks fuzzy to me.

Why root logger is not configured? How config is propagated to the child loggers when they don't have  `atomic_reactor.*` prefix?

https://docs.python.org/3/howto/logging-cookbook.html

**Comment by MartinBasti** [comment]
* logging is configured during import time of `set_logging method`, we shouldn't do that, loggin should be configured in main application.
* osbs client configures logging too, libraries should not configure logging, they even should have logging disabled by: https://docs.python.org/3/howto/logging.html#library-config (nto sure about py2)
* we don't configure root handler, every logger out of `osbs.*`/`atomic_reactor.*` patterns will pass log entries to root logger which will use default behavior (logs >=WARNING message to stderr), messages with lower loglevel will be discarded even if they come from atomic_reactor
* we don't enforce osbs/atomic_reactor prefix for sub-loggers, for example `atomic_reactor/util.py`. Log entries from that file may be lost, WARNING+ entries incorrectly formatted.
* nice example of configuring loggers: https://docs.python.org/3/howto/logging-cookbook.html#an-example-dictionary-based-configuration

**Comment by MartinBasti** [comment]
I didn't want to block this PR, for logging changes we may new a separate issue. This PR works fine for now.

**Comment by rcerven** [comment]
rn updated: - Propagate logging level to osbs-client

**Pull request merged**
