### PR TITLE
Add minimal support for docker-py-2.x module

### PR DESCRIPTION
**Pull request by twaugh**
@maxamillion, something to test when using a rawhide- or f26-based buildroot.

### CODE REVIEW

**Comment by vrutkovs** [comment]
It looks fine to me, maybe its worth adding a new configuration to travis where docker-py 2 would be installed?

**Comment by twaugh** [comment]
Not sure it's worth adding it to Travis: we mock the docker module completely in unit tests.

**Comment by maxamillion** [comment]
I'll try to test this asap, kind of under water with some other stuff though so it'll be a bit.

**Comment by twaugh** [comment]
@maxamillion, had any time for this?

**Comment by maxamillion** [comment]
@twaugh I have not, but I'd be amazed if this caused any issues so please don't hold this up on my account. Apologies on the lag time as well as if this has been blocked by me for any reason.

**Comment by twaugh** [comment]
Rebased, and updated to make the test suite pass when python-docker 2.x is installed.

**Comment by vrutkovs** [comment]
Looks good so far, I'll check if it works in latest rawhide on osbs box

**Comment by vrutkovs** [comment]
Crashes here - https://gist.github.com/vrutkovs/bdb44bb52b305c70d26516898d24a347

Tested on F26 osbs-box with Dockerfile: https://gist.github.com/vrutkovs/e6ddfba090f8214d1b31dedf4b3d44fa

**Comment by vrutkovs** [comment]
Okay, now got a valid crash:
```
2017-07-14 13:10:44,030 platform:- - atomic_reactor.plugin - DEBUG - running plugin 'pull_base_image'
2017-07-14 13:10:44,030 platform:- - atomic_reactor.plugin - INFO - running plugin instance with args: '{u'parent_registry_insecure': True, u'parent_registry': u'registry.fedoraproject.org'}'
2017-07-14 13:10:44,031 platform:- - atomic_reactor.plugins.pull_base_image - INFO - pulling base image 'fedora:latest' from registry 'registry.fedoraproject.org'
2017-07-14 13:10:44,031 platform:- - atomic_reactor.core - INFO - pulling image 'registry.fedoraproject.org/fedora:latest' from registry
2017-07-14 13:10:44,031 platform:- - atomic_reactor.core - DEBUG - image = 'registry.fedoraproject.org/fedora:latest', insecure = 'True'
2017-07-14 13:10:44,086 platform:- - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugin.py", line 241, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor/plugins/pre_pull_base_image.py", line 63, in run
    insecure=self.parent_registry_insecure)
  File "/usr/lib/python2.7/site-packages/atomic_reactor/core.py", line 435, in pull_image
    insecure_registry=insecure, stream=True)
  File "/usr/lib/python2.7/site-packages/docker/api/image.py", line 358, in pull
    header = auth.get_config_header(self, registry)
AttributeError: 'module' object has no attribute 'get_config_header'
2017-07-14 13:10:44,106 platform:- - atomic_reactor.plugin - ERROR - plugin 'pull_base_image' raised an exception: AttributeError("'module' object has no attribute 'get_config_header'",)
2017-07-14 13:10:44,107 platform:- - atomic_reactor.inner - ERROR - one or more prebuild plugins failed: plugin 'pull_base_image' raised an exception: AttributeError("'module' object has no attribute 'get_config_header'",)
```

Since Tim is on PTO next week I'll try to come up with a fix and push it to the branch

**Comment by twaugh** [comment]
Draft release notes updated.

**Comment by maxamillion** [comment]
FWIW, this is live in production in Fedora Infra now and it works great.

**Comment by twaugh** [comment]
Great! Thanks for letting us know.

**Pull request merged**
