### PR TITLE
core,push: use wait_for_command for parsing logs

### PR DESCRIPTION
**Pull request by TomasTomecek**
I've just realized this slightly conflicts with @twaugh's patch: https://github.com/projectatomic/atomic-reactor/commit/a770fdc20efda4b46ff8a9baf2031dd415994fff

### CODE REVIEW

**Comment by twaugh** [comment]
Maybe `push_image` could raise an exception if `command_result.is_failed()`? Then the plugin change I made could be backed out.

**Comment by TomasTomecek** [comment]
great idea, will incorporate

**Comment by TomasTomecek** [comment]
PTAL

**Comment by twaugh** [comment]
Now `DockerTasker.push_image()` returns unparsed logs. It used to return parsed logs. The `tag_and_push` plugin needs parsed logs in order to find out the manifest digest.

For the tests to pass we'd need to change `tests/plugins/test_tag_and_push.py` so that it uses `iter(logs)` instead of `logs` when mocking docker-py's push method, and `wait_for_command` so that it adds `parsed_item` instead of `item` to the logs list.

**Comment by TomasTomecek** [comment]
Thanks Tim, will update.

**Comment by TomasTomecek** [comment]
Done.

(expected this to be a small patch)

will add more tests to make coveralls happy

**Comment by twaugh** [comment]
With this change we could also remove the explicit error checking from post_tag_and_push (see last commit).

**Comment by TomasTomecek** [comment]
didn't realize; very nice Tim!

**Comment by TomasTomecek** [comment]
can we merge this now?

**Comment by twaugh** [comment]
LGTM

**Comment by TomasTomecek** [comment]
Thanks Tim!

**Pull request merged**
