### PR TITLE
bump_release: deal with pygit2-0.22/23 changes (fixes #285)

### LINKED ISSUE #285: plugin 'bump_release' raised an exception: 'AttributeError("can't set attribute",)'
Steps to reproduce:
$ dnf install python-pygit2
$  py.test -vv -x tests/plugins/test_bump_release.py

```
atomic_reactor.plugin - DEBUG - running plugin 'bump_release'
atomic_reactor.plugin - INFO - running plugin instance with args: '{u'author_email': u'root@example.com', u'git_ref': '84be20b445b9cebddc0890bdff431587815d3efc', u'author_name': u'OSBS Build System', u'push_url': u'/', u'commit_message': u'foo'}'
atomic_reactor.plugins.bump_release - INFO - Incrementing release label
atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 260, in run
    self.bump(repo, branch)
  File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 169, in bump
    remote.push_url = self.push_url
AttributeError: can't set attribute
```

### PR DESCRIPTION
**Pull request by twaugh**

### CODE REVIEW

**Comment by jpopelka** [comment]
Still the same, i.e.

```
File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 107, in bump
    remote.push_url = self.push_url
AttributeError: can't set attribute
```

When I remove the `try:except:`
and leave only
```
if self.push_url:
    remote.set_push_url(self.push_url)
```
I see:
```
File "/home/jpopelka/git/atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 102, in bump
    remote.set_push_url(self.push_url)
File "/home/jpopelka/git/atomic-reactor/tests/plugins/test_bump_release.py", line 120, in set_push_url
    raise AttributeError("no such attribute 'set_push_url'")

**Comment by twaugh** [comment]
I mis-read the documentation. The new `set_push_url()` method is on the `RemoteCollection` not the `Remote`.

Could you try again now?

**Comment by jpopelka** [comment]
```
File "atomic-reactor/atomic_reactor/plugins/pre_bump_release.py", line 110, in bump
    remote.save()
File "/usr/lib64/python2.7/site-packages/pygit2/remote.py", line 165, in save
    err = C.git_remote_save(self._remote)
AttributeError: 'FFILibrary' object has no attribute 'git_remote_save'
```

**Comment by twaugh** [comment]
OK, understood. The new `RemotesCollection.set_push_url()` method replaces both the `Remote.push_url` attribute and the `Remote.save()` method.

Fixed.

**Comment by jpopelka** [comment]
LGTM

**Pull request merged**
