### PR TITLE
Construct NVR string early and fail in pre_koji if build was already submitted

### PR DESCRIPTION
**Pull request by vrutkovs**
TODO:
 * [x] Add tests

### CODE REVIEW

**Comment by twaugh** [comment]
This plugin doesn't get run at all if a yum repourl is specified for the build, so the check won't be performed when building with signed packages.

**Comment by vrutkovs** [comment]
Right, we probably don't need it if https://github.com/release-engineering/koji-containerbuild/pull/38 will be accepted, although it might help if osbs cli is used.

**Comment by vrutkovs** [comment]
We probably don't need this one after koji-containerbuild change has landed?

**Comment by twaugh** [comment]
Probably not.

**Comment by vrutkovs** [comment]
Closing this one for now - this is implemented in k-cb now

**Pull request closed without merging**
