### PR TITLE
koji_promote: include v2 digests in metadata

### PR DESCRIPTION
**Pull request by mmilata**
@twaugh, in your original patch there is some logic to avoid duplicates in the list of repositories - can this happen? Do we expect to push to one registry multiple times?

### CODE REVIEW

**Comment by twaugh** [comment]
Nice!

But yes, when we're using both V1 and V2 we can end up generating this metadata:
```
                "docker": {
                    "id": "123456imageid",
                    "parent_id": "123456parent-id",
                    "repositories": [
                        "pulp.example.com/ns/name:1.0-1",
                        "pulp.example.com/ns/name@sha256:0000000000000000000000000000000d",
                        "pulp.example.com/ns/name:1.0-1",
                        "pulp.example.com/ns/name@sha256:0000000000000000000000000000000d"
                    ]
                },
```

(try `py.test-3 -k promote_success -v tests -s`)

**Comment by twaugh** [comment]
We should maybe add a check for duplicates in the test-case, come to think of it.

**Comment by mmilata** [comment]
Added a commit to avoid duplicates. Can squash it into the previous one if you want.

**Comment by twaugh** [comment]
LGTM. Happy for you to squash and merge.

**Pull request merged**
