### PR TITLE
check_and_set_rebuild: retry on conflict

### LINKED ISSUE #397: check_and_set_rebuild: occasional 409
I sometimes see this:

```
2015-12-11 11:52:56,818 - atomic_reactor.plugin - DEBUG - Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugin.py", line 203, in run
    plugin_response = plugin_instance.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.6.0-py2.7.egg/atomic_reactor/plugins/pre_check_and_set_rebuild.py", line 106, in run
    osbs.set_labels_on_build_config(buildconfig, labels, **kwargs)
  File "build/bdist.linux-x86_64/egg/osbs/api.py", line 33, in catch_exceptions
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/osbs/api.py", line 454, in set_labels_on_build_config
    namespace=namespace)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 501, in set_labels_on_build_config
    namespace=namespace)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 472, in adjust_attributes_on_object
    check_response(response)
  File "build/bdist.linux-x86_64/egg/osbs/core.py", line 47, in check_response
    raise OsbsResponseException(message=content, status_code=response.status_code)
OsbsResponseException: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "buildconfig \"docker-hello-world-master\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
  "reason": "Conflict",
  "details": {
    "name": "docker-hello-world-master",
    "kind": "buildconfig"
  },
  "code": 409
}
```
I think it must be some sort of race condition, but in any case it ought to retry. Or should this be done in `Openshift.set_labels_on_build_config()`?

### PR DESCRIPTION
**Pull request by twaugh**
Fixes #397.

### CODE REVIEW

**Comment by jpopelka** [comment]
LGTM

**Comment by mmilata** [comment]
LGTM, however if we encounter this again with something else I'd suggest to move the retrying code into `Openshift.adjust_attributes_on_object` or some other place in OSBS.

**Comment by twaugh** [comment]
Agreed.

**Comment by mmilata** [comment]
Merging, thank you!

**Pull request merged**
