### PR TITLE
Koji build 'output' metadata for tags

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Revert of https://github.com/projectatomic/atomic-reactor/pull/818

**Comment by twaugh** [comment]
Comment ought to explain why this is needed.

**Comment by rcerven** [comment]
explanation added to the commit message

**Comment by lcarva** [comment]
Updated release notes draft:

> - 'tags' field in Koji build metadata includes the worker's platform-specific unique tag when `group_manifests=true`

**Pull request merged**
