### PR TITLE
Move pulling base image into a plugin

### LINKED ISSUE #218: Move pulling base image into a plugin
@pbabinca's proposal for scratch builds suggests that if there is `FROM xyz` in the Dockerfile then we should first try pulling `scratch-xyz` as a base image.

Moving the pulling logic into a plugin would make the implementation less messy since we need to know if the build is a scratch build, which can be easily passed as a parameter to the plugin.

### PR DESCRIPTION
**Pull request by mmilata**
For backwards compatibility the plugin is automatically enabled when not explicitly listed - we can remove that once we're sure everyone's osbs-client is updated.

Closes #218.

### CODE REVIEW

**Comment by jpopelka** [comment]
@mmilata your change LGTM, please review mine addition, thanks

**Comment by TomasTomecek** [comment]
This is definitely something we should aim for. The only problem I have with current implementation is the code in `inner.py`. I think this is where we should probably introduce build types. Because I think that configuration of pulling base image should be as simple as possible. We should not force users to write json.

**Comment by mmilata** [comment]
@jpopelka Thank you! I'll try running the tests with `NOMOCK=1` next time.

@TomasTomecek Right, I didn't realize that when the code that automatically enables the plugin is removed it becomes impossible to start a build from API without providing a build json. Does this mean we need to solve #85 before moving the base image code to a plugin?

**Comment by mmilata** [comment]
I've fixed the issue with cli/api builds based on offline discussion with @TomasTomecek. I also removed the `change_source_registry` plugin which doesn't do anything when pulling base image happens in a plugin.

**Comment by twaugh** [comment]
Would be nice to see a couple of tests in `tests/plugins/test_pull_base_image.py` for the new plugin.

**Comment by twaugh** [comment]
Oh, ignore me, I missed them before.

Looks good to me.

**Comment by mmilata** [comment]
Found a little bug, pushing once again ...

**Comment by mmilata** [comment]
Rebased.

**Comment by TomasTomecek** [comment]
LGTM, nice work!

**Pull request merged**
