### PR TITLE
bump_release: support git < 2.3 by using GIT_SSH instead of GIT_SSH_COMMAND

### PR DESCRIPTION
**Pull request by twaugh**
This is required for build roots using e.g. RHEL-7.

### CODE REVIEW

**Comment by jpopelka** [comment]
LGTM

**Comment by mmilata** [comment]
LGTM. Just curious, why create temporary directory and then a file in it instead of just creating temporary file?

**Comment by twaugh** [comment]
For one reason only: `ps` will show a useful name for arg 0.

**Comment by mmilata** [comment]
That's good reason. Thanks!

**Pull request merged**
