### PR TITLE
Plugin for promoting builds to Content Generator API

### PR DESCRIPTION
**Pull request by twaugh**
Here is a plugin for using the Content Generator API to submit successful builds to Koji.

Please do not merge yet as the XMLRPC interface is not yet specified and the metadata format definition is not yet final.

Review comments are still useful, however.

### CODE REVIEW

**Comment by twaugh** [comment]
Fixes #307.

**Comment by twaugh** [comment]
Thanks for comments, should all be addressed now.

**Comment by jpopelka** [comment]
Otherwise LooksVeryGoodToMe so far.

**Comment by twaugh** [comment]
I've removed the `constants.VERSION` constant and now use `pkg_resources.get_distribution(PROG).version` for getting the version of atomic-reactor.

**Comment by bkabrda** [comment]
I suggest putting `__version__` to `atomic_reactor/__init__.py`. It's PEP-396 standardized way of doing this.

[1] https://www.python.org/dev/peps/pep-0396/#specification

**Comment by twaugh** [comment]
Sure, but there's a problem to solve there, isn't there? i.e. how do we keep that version in just one place? What method would you suggest?

**Comment by bkabrda** [comment]
From my experience, it's usually best to just keep version in more places (in our case that would be specfile, setup.py and __init__.py). It is unfortunate, but it seems to me that all the other methods I've seen are flawed (like importing __init__.py from setup.py, parsing it, etc...) I'm afraid I don't have a better answer for this.

**Comment by twaugh** [comment]
Example metadata generated by the plugin: https://gist.github.com/twaugh/b2967d37906fc7a010b4

**Comment by TomasTomecek** [comment]
Will `buildroots → components` list every rpm in buildroot?

**Comment by twaugh** [comment]
Yes, everything that isn't named `gpg-pubkey`.

**Comment by twaugh** [comment]
Ready for review.

**Comment by jpopelka** [comment]
LGTM

**Comment by twaugh** [comment]
Sample metadata: https://gist.github.com/twaugh/b2967d37906fc7a010b4
(from `py.test -k promote_success -s`)

**Comment by twaugh** [comment]
I've added support for specifying the Kerberos principal and keytab.

**Comment by jpopelka** [comment]
LGTM

**Comment by twaugh** [comment]
Re-based to solve conflicts.

**Comment by twaugh** [comment]
Sample metadata output updated:
 * v1 image: https://gist.github.com/twaugh/b2967d37906fc7a010b4
 * metadata-only: https://gist.github.com/twaugh/71096604ee6f2862b1ce

**Comment by twaugh** [comment]
Anyone willing to merge this?

**Comment by mmilata** [comment]
Good job, merged!

**Pull request merged**
