### PR TITLE
Support LABEL-ENV indirection in bump_release

### PR DESCRIPTION
**Pull request by twaugh**
This depends on two features in `dockerfile-parse`: the ability to set `parser.envs[...]` attributes and optional environment variable substitution.

Once there is a 0.0.5 release I'll update `requirements.txt` and remove the version tests from `tests/plugins/test_bump_release.py`.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
LGTM

**Comment by twaugh** [comment]
The 0.0.5 release of `dockerfile_parse` is out so this is now ready for merge.

**Comment by twaugh** [comment]
Updated.

**Comment by jpopelka** [comment]
Perfect, squashed & merged.

**Pull request merged**
