### PR TITLE
Use the new label set

### PR DESCRIPTION
**Pull request by mmilata**
Depends on #342.

### CODE REVIEW

**Comment by twaugh** [comment]
I think this needs to add support for the new label set without removing support for the old.

**Comment by mmilata** [comment]
Do you mean that we shouldn't add the new tags when only old tags are present (as described in #342) and make other plugins work with both sets instead?

**Comment by twaugh** [comment]
No, I didn't understand #342 properly. I do now, looks fine.

**Comment by jpopelka** [comment]
LGTM once you rename `rename_labels` -> `aliases` in `test_add_dockerfile`

**Comment by mmilata** [comment]
Updated. I should probably read the code I wrote sometimes ...

**Comment by mmilata** [comment]
Added another commit that makes `bump_release` detect the label that it should use. The reasons are outlined in https://github.com/projectatomic/osbs-client/pull/266#issuecomment-146520158. I'll squash it to the previous commit when ready to merge.

**Comment by jpopelka** [comment]
LGTM

**Comment by mmilata** [comment]
Squashed & rebased.

**Comment by twaugh** [comment]
Should this still say '[do not merge]' in the title?

**Comment by mmilata** [comment]
I'm not sure, what do you think @TomasTomecek?

**Comment by mmilata** [comment]
I've added commit that allows plugins to use the old label if the new one is not present. This PR can be merged now without breaking builds initiated by osbs without projectatomic/osbs-client#266 (currently `add_dockerfile` is run before `add_labels`).

Landscape seems to complain about false positives here?

**Comment by TomasTomecek** [comment]
This looks really good. LGTM

**Pull request merged**
