### PR TITLE
orchestrate: reraise BuildCanceledException if its raised when fetching builds from worker cluster

### PR DESCRIPTION
**Pull request by vrutkovs**
This resolves the following bug:
* an orchestration build is started with one of the faulty worker clusters is started
* during 'get_current_builds' function the build gets cancelled
* http.py wraps atomic-reactor's BuildCanceledException in OsbsException
* osbs-client's 'get_current_builds' skips OsbsException and moves on to next cluster

The fix is to check the cause of OsbsException and reraise the exception if its 
BuildCanceledException

### CODE REVIEW

**Comment by vrutkovs** [comment]
Not sure if an additional test for this is needed

**Comment by twaugh** [comment]
Would be nice to, so we have coverage over that line.

**Comment by vrutkovs** [comment]
Test added, PTAL

**Comment by twaugh** [comment]
Doesn't need updates to the draft release notes.

**Pull request merged**
