### PR TITLE
squash: don't load result if dont_load==True

### PR DESCRIPTION
**Pull request by mmilata**
docker-scripts default is to load the image: https://github.com/goldmann/docker-scripts/blob/0.4.4/docker_scripts/squash.py#L38

### CODE REVIEW

**Comment by jpopelka** [comment]
Agree, LGTM.

**Comment by TomasTomecek** [comment]
Very nice! LGTM

**Comment by TomasTomecek** [comment]
I missclicked -,-

**Comment by twaugh** [comment]
Oh, *that*'s what causes it!

**Pull request merged**
