### PR TITLE
flatpak_create_oci: Sanitize file permissions and ownership

### PR DESCRIPTION
**Pull request by owtaylor**
When we are exporting the filesystem, match the permission and
ownership changes done by 'flatpak build-export'. In addition to
replacing the existing fixup for read-only files, this handles other
cases that could cause problems, such as setuid binaries or
world-writable directories.

### CODE REVIEW

**Comment by vrutkovs** [comment]
Needs a rebase to resolve merge conflicts

**Comment by vrutkovs** [comment]
That's weird - Travis build has started failing after the rebase

**Comment by owtaylor** [comment]
Yeah, I made a mistake in the rebase, pushed a new version now. The problem was that the patch fixed a bug:

    - if config_name is 'app'
    + if config_name == 'app'

which *sometimes* failed to match, depending on the details of the python version, and I lost that fix with the rebase (it was in an area with conflicts.)

**Comment by vrutkovs** [comment]
Ah, `is` is tricky indeed. I'll merge it after tests are complete

**Pull request merged**
